vozfake/forums/urls.py
from django.urls import path

from . import views

app_name = 'forums'

urlpatterns = [
	path('', views.IndexView.as_view(),name = 'index'),
	path('f=<int:subforum_id>/',views.detailSubforum, name = 'sub_forum'),
	path('t=<int:thread_id>/',views.detailThread, name='thread'),
	#path('tinh-lich-tra-no-giam-dan',views.loanInfo, name = 'loan_info'),
	path('tinh-lich-tra-no-giam-dan',views.loanInfo_djangoForm, name = 'loaninfo_django'),
	path('lich-tra-no-chi-tiet/<int:start_principal>+<str:start_date_str>+<str:ir_str>+<int:periods>',views.repaymentSchedule, name = 'loan_repayment')
]

vozfake/vozfake/urls.py
from django.contrib import admin
from django.urls import path, include

import forums.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forums/',include('forums.urls')),
    path('',include('forums.urls'))
]

vozfake/forums/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class SubForum(models.Model):
	sub_forum_name = models.CharField(max_length = 200)

	def __str__(self):
		return self.sub_forum_name


class Thread(models.Model):
	thread_name = models.CharField(max_length=200)
	thread_content = models.TextField()
	created_by = models.ForeignKey(User,on_delete=models.CASCADE) #delete thread if user is deleted
	created_on = models.DateTimeField('date created')
	parent = models.ForeignKey(SubForum, on_delete=models.PROTECT) #subforum cannot be deleted
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.thread_name

class Post(models.Model):
	posted_by = models.ForeignKey(User, on_delete=models.CASCADE) #delete post if user is deleted
	post_text = models.TextField()
	parent = models.ForeignKey(Thread,on_delete=models.CASCADE) #if thread is deleted, post will be deleted
	post_time = models.DateTimeField('date posted')
	
	def __str__(self):
		post_info = self.posted_by + self.post_time
		return post_info

vozfake/forums/forms.py
from django import forms

class LoanInfo(forms.Form):
	start_principal = forms.CharField(max_length=14)
	periods = forms.IntegerField(max_value=600,min_value=1)
	ir = forms.DecimalField(max_value = 20.00,min_value =0.00,decimal_places=2,max_digits=4)
	start_date = forms.DateField()

vozfake/forums/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

import numpy as np
import pandas as pd
from datetime import date

from .models import SubForum, Thread, Post
from .forms import LoanInfo
from .interest_module import loanRepayment
# Create your views here.

#MARK: Class-based views
class IndexView(generic.ListView):
	template_name = 'forums/index.html'
	context_object_name = 'subforum_list'
	
	def get_queryset(self):
		return SubForum.objects.all()

#MARK: Function-based views
def detailSubforum(request,subforum_id):
	subforum = get_object_or_404(SubForum,pk=subforum_id)
	#thread_list = Thread.objects.filter(parent=subforum).order_by('-created_on')
	context = {'subforum': subforum}
	return render(request,'forums/subforum.html',context)

def detailThread(request,thread_id):
	thread = Thread.objects.get(id = thread_id)
	context = {'thread': thread}
	thread.views +=1
	thread.save()
	return render(request,'forums/thread.html',context)	

# def loanInfo(request):
# 	template = loader.get_template('forums/loaninfo.html')
# 	return HttpResponse(template.render())

def loanInfo_djangoForm(request):
	if request.method == 'POST':
		loan_form = LoanInfo(request.POST)
		if loan_form.is_valid():
			start_principal = int(loan_form.cleaned_data['start_principal'].replace(",",""))
			start_date = loan_form.cleaned_data['start_date']
			ir = loan_form.cleaned_data['ir']/100
			periods = loan_form.cleaned_data['periods']			

			return HttpResponseRedirect(reverse('forums:loan_repayment',args=(start_principal,start_date,ir,periods)))

	else:
		loan_form = LoanInfo()
	
	return render(request,'forums/loaninfo_v2.html',{'loan_form':loan_form})

def repaymentSchedule(request,start_principal,start_date_str,ir_str,periods):
	#convert date string to type date
	start_date = date.fromisoformat(start_date_str)
	
	#convert interest rate string to type float
	ir = float(ir_str)
	schedule = loanRepayment(start_principal,start_date,ir,periods)

	#calculate variables for display purpose
	monthly_principal = int(start_principal/periods)
	total_interest = int(np.sum(schedule['Monthly interest']))
	total_payment = int(start_principal + total_interest)

	context = {
		'df':schedule,
		'start_principal':start_principal,
		'start_date':start_date,
		'periods':periods,
		'ir':round(ir*100,2),
		'monthly_principal':monthly_principal,
		'total_principal':start_principal,
		'total_interest':total_interest,
		'total_payment':total_payment
		}

	return render(request,'forums/repaymentschedule.html',context)

vozfake/forums/templates/forums/index.html
<!DOCTYPE html>
<html>
<head>
	<title>vozFake - Vì một voz không dốt toán</title>
	{% load static %}
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'forums/vozfavicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'forums/vozfavicon-16x16.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'forums/bootstrap.min.css' %}">
</head>
<body style="background-color: black">
	<div class="container">
		<a href="{% url 'forums:index' %}">
			<img src="{% static 'forums/vozlogo.gif' %}" border="0" alt="vozForums" width="184" height="90" title="vozForums">
		</a>
	</div>
	<div class="container" style="background-color: #f2f2f2">
		
		<table class="table table-hover table-border">
			<thead class="bg-secondary text-white">
				<tr>
					<th>Forum</th>
					<th>Threads</th>
					<th>Views</th>
				</tr>
			</thead>
			<tbody>
				{% if subforum_list %}
				{% for subforum in subforum_list %}
					<tr>
						<td><a href="{% url 'forums:sub_forum' subforum.id %}">{{ subforum.sub_forum_name }}</a></td>
						<td>{{ subforum.thread_set.count }}</td>
						<td></td>
					</tr>
				{% endfor %}
				{% else %}
					<p>No forums are available.</p>
				{% endif %}

				<tr>
					<td><a href="{% url 'forums:loaninfo_django' %}">Tính lịch trả nợ kiểu Django</a></td>
					<td></td>
					<td></td>
				</tr>
			</tbody>
		</table>
	</div>
</body>
</html>

vozfake/forums/templates/forums/loaninfo.html
<!DOCTYPE html>
<html>
<head>
	<title>Tính lịch trả nợ kiểu VOZ - Thông tin khoản vay</title>
	{% load static %}
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'forums/vozfavicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'forums/vozfavicon-16x16.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'forums/bootstrap.min.css' %}">
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
	<script type="text/javascript">
		function setInputFilter(textbox, inputFilter) {
  			["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function(event) {
				    textbox.addEventListener(event, function() {
				      if (inputFilter(this.value)) {
				        this.oldValue = this.value;
				        this.oldSelectionStart = this.selectionStart;
				        this.oldSelectionEnd = this.selectionEnd;
				      } else if (this.hasOwnProperty("oldValue")) {
				        this.value = this.oldValue;
				        this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
				      } else {
				        this.value = "";
				      }
				    });
 				 });
  		function addCommas(nStr)
		{
		    nStr += '';
		    x = nStr.split('.');
		    x1 = x[0];
		    x2 = x.length > 1 ? '.' + x[1] : '';
		    var rgx = /(\d+)(\d{3})/;
		    while (rgx.test(x1)) {
		        x1 = x1.replace(rgx, '$1' + ',' + '$2');
		    }
		    return x1 + x2;
		}
}	</script>
</head>
<body style="background-color: black">
	<div class="container">
		<a href="{% url 'forums:index' %}">
			<img src="{% static 'forums/vozlogo.gif' %}" border="0" alt="vozForums" width="184" height="90" title="vozForums">
		</a>
	</div>
	<div class="container" style="background-color: #f2f2f2">
		<form action="{% url 'forums:loan_repayment' %}" method="post">
		{% csrf_token %}
		<table class="table">
			<tr style="padding: 5px">
				<td><label>Số tiền vay </label></td>
				<td>
					<input type="text" name="principal" id="money" maxlength="14" style="text-align: right;"> VND
					<!-- cái này để format số tiền -->
					<script type="text/javascript">
						jQuery("#money").keyup(function () {
			                var str = jQuery(this).val();
			                str = str.replace(/\D+/g, '');
			                str = str.replace(/^(0*)/, '');
			                jQuery(this).val(str.replace(/\d(?=(?:\d{3})+(?!\d))/g, '$&,'));
			            });
					</script>
										
				</td>
			</tr>
			<tr>
				<td><label>Thời gian vay </label></td>
				<td><input type="text" maxlength="3" id="periods" name="periods" style="text-align: right;"> tháng</td>
				<!-- cái này để chỉ cho phép nhập số: -->
				<script type="text/javascript">
					setInputFilter(document.getElementById("periods"), function(value) {
							return /^\d*\.?\d*$/.test(value); // Allow digits and '.' only, using a RegExp
						});
        		</script>
			</tr>
			<tr>
				<td><label>Lãi suất </label></td>
				<td><input type="text" name="ir" maxlength="5" id="ir" style="text-align: right;"> %/năm
					<script type="text/javascript">
					setInputFilter(document.getElementById("ir"), function(value) {
							return /^\d*\.?\d*$/.test(value); // Allow digits and '.' only, using a RegExp
						});
        			</script>
				</td>
			</tr>
			<tr>
				<td><label>Ngày giải ngân </label></td>
				<td><input type="text" name="start_date" id="datetimepicker" placeholder="Click để chọn ngày" style="text-align: right;"> mm/dd/yyyy
				<script type="text/javascript">
					$(function () {
						$('#datetimepicker').datepicker();
					})
				</script></td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="submit" value="Tính" class="btn" style="background-color: green;color: white">				
					<input type="reset" value="Clear" class="btn" style="background-color: red;color: white">
				</td>				
			</tr>
		</table>
		</form>
								
	</div>
</body>
</html>

vozfake/forums/templates/forums/loaninfo_v2.html
<!DOCTYPE html>
<!-- use Django form -->
<html>
<head>
	<title>Tính lịch trả nợ kiểu VOZ - Thông tin khoản vay</title>
	{% load static %}
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'forums/vozfavicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'forums/vozfavicon-16x16.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'forums/bootstrap.min.css' %}">
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
	<script type="text/javascript">
		function setInputFilter(textbox, inputFilter) {
  			["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function(event) {
				    textbox.addEventListener(event, function() {
				      if (inputFilter(this.value)) {
				        this.oldValue = this.value;
				        this.oldSelectionStart = this.selectionStart;
				        this.oldSelectionEnd = this.selectionEnd;
				      } else if (this.hasOwnProperty("oldValue")) {
				        this.value = this.oldValue;
				        this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
				      } else {
				        this.value = "";
				      }
				    });
 				 });
  		function addCommas(nStr)
		{
		    nStr += '';
		    x = nStr.split('.');
		    x1 = x[0];
		    x2 = x.length > 1 ? '.' + x[1] : '';
		    var rgx = /(\d+)(\d{3})/;
		    while (rgx.test(x1)) {
		        x1 = x1.replace(rgx, '$1' + ',' + '$2');
		    }
		    return x1 + x2;
		}
}	</script>
</head>
<body style="background-color: black">
	<style type="text/css">
		#id_ir,#id_start_principal,#id_periods{
			width: 100%;
			text-align: right;
		}
		#id_start_date{
			width: 100%;
			text-align: right;

		}
	</style>
	<div class="container">
		<a href="{% url 'forums:index' %}">
			<img src="{% static 'forums/vozlogo.gif' %}" border="0" alt="vozForums" width="184" height="90" title="vozForums">
		</a>
	</div>
	<div class="container" style="background-color: #f2f2f2, margin:10px">
		<form  method="post">
			{% csrf_token %}
			{{ loan_form.non_field_errors }}
			}
		<table class="table-primary">
			<tr>
				{{ loan_form.start_principal.errors }}
				<td>Số tiền vay</td>
				<td style="text-align: right;">{{ loan_form.start_principal }}</td>
				<td> VND</td>
				<script type="text/javascript">
						jQuery("#id_start_principal").keyup(function () {
			                var str = jQuery(this).val();
			                str = str.replace(/\D+/g, '');
			                str = str.replace(/^(0*)/, '');
			                jQuery(this).val(str.replace(/\d(?=(?:\d{3})+(?!\d))/g, '$&,'));
			            });
				</script>
			</tr>
			<tr>
				{{ loan_form.periods.errors }}
				<td>Thời gian vay</td>
				<td style="text-align: right;">{{ loan_form.periods }}</td>
				<td> tháng</td>
			</tr>
			<tr>
				{{ loan_form.ir.errors }}
				<td>Lãi suất</td>
				<td>{{ loan_form.ir }}</td>
				<td> %/năm</td>
			</tr>
			<tr>
				{{ loan_form.start_date.errors }}
				<td>Ngày giải ngân</td>
				<td style="text-align: right;">{{ loan_form.start_date }}</td>
				<script type="text/javascript">
				  	$(function () {
						$('#id_start_date').datepicker();
					})
				 </script>
				<td> mm/dd/yyyy</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<input type="submit" value="Tính" class="btn" style="background-color: green;color: white">				
					<input type="reset" value="Clear" class="btn" style="background-color: red;color: white">
				</td>				
			</tr>
		</table>
		</form>
								
	</div>
</body>
</html>

vozfake/forums/templates/forums/repaymentschedule.html
<!DOCTYPE html>
<html>
<head>
	<title>Tính lịch trả nợ kiểu VOZ - Lịch trả nợ chi tiết</title>
	{% load static %}
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'forums/vozfavicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'forums/vozfavicon-16x16.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'forums/bootstrap.min.css' %}">
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
</head>
<body style="background-color: black">
	<div class="container">
		<a href="{% url 'forums:index' %}">
			<img src="{% static 'forums/vozlogo.gif' %}" border="0" alt="vozForums" width="184" height="90" title="vozForums">
		</a>
	</div>
	{% load humanize %}
	<div class="container" style="background-color: #f2f2f2">
		<h4>
			<a href="{% url 'forums:index' %}">Forum</a> > Lịch trả nợ chi tiết
		</h4>
		<b><h5>Thông tin khoản vay</h5></b>
		<div class="row">
			<div class="col">Số tiền vay:</div><div class="col" style="text-align: right;">{{ start_principal|intcomma }} VND</div><div class="col-8"></div>
		</div>
		<div class="row">
			<div class="col">Thời gian vay:</div><div class="col" style="text-align: right;">{{ periods|intcomma }} tháng</div><div class="col-8"></div>
		</div>
		<div class="row">
			<div class="col">Lãi suất:</div><div class="col" style="text-align: right;">{{ ir|intcomma }}%/năm</div><div class="col-8"></div>
		</div>
		<div class="row" style="margin-bottom: 10px">
			<div class="col">Ngày giải ngân: </div><div class="col" style="text-align: right;">{{ start_date }}</div><div class="col-8"></div>
		</div>
		
	</div>
	<div class="container" style="background-color: #f2f2f2">
		
		<table class="table table-border table-hover table-striped">
			<thead class="thead-dark" style="text-align: right;">
				
					<th style="text-align: left;">Ngày trả nợ</th>
					<th>Gốc vay đầu kỳ</th>
					<th>Trả gốc</th>
					<th>Trả lãi</th>
					<th>Tổng trả</th>
					<th>Gốc vay cuối kỳ</th>
				
			</thead>			
			<tbody>
				<!-- load humanize to format number with thousand separator -->
				
				{% for row in df.itertuples %}
				<tr style="text-align: right;">					
					<td style="text-align: left;">{{ row.1|date:"Y-m-d" }}</td>
					<td>{{ row.2|intcomma }}</td>
					<td>{{ monthly_principal|intcomma }}</td>
					<td>{{ row.3|intcomma }}</td>
					<td>{{ row.4|intcomma }}</td>
					<td>{{ row.5|intcomma }}</td>					
				</tr>
				{% endfor %}

				<tr style="background-color: indigo;color: white;text-align: right;">
					<b>
					<td style="text-align: left;">Tổng</td>
					<td></td>
					<td>{{ total_principal|intcomma }}</td>
					<td>{{ total_interest|intcomma }}</td>
					<td>{{ total_payment|intcomma }}</td>
					<td></td>
					</b>
				</tr>
			</tbody>
		</table>
	</div>
</body>
</html>

vozfake/forums/templates/forums/subforum.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ subforum.sub_forum_name }}</title>
	{% load static %}
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'forums/vozfavicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'forums/vozfavicon-16x16.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'forums/bootstrap.min.css' %}">
</head>
<body style="background-color: black">
	<div class="container">
		<a href="{% url 'forums:index' %}">
			<img src="{% static 'forums/vozlogo.gif' %}" border="0" alt="vozForums" width="184" height="90" title="vozForums">
		</a>
	</div>
	<div class="container bg-white">

		<h4><a href="{% url 'forums:index' %}">Forum</a> > {{ subforum.sub_forum_name }}</h4>
	</div>
	<div class="container" style="background-color: #f2f2f2">
		<table class="table table-border table-hover">
			<thead class="bg-secondary text-white">
				<tr>
					<th>Thread</th>
					<th>Replies</th>
					<th>Views</th>
				</tr>
			</thead>
			<tbody>
				{% if subforum.thread_set.all %}
				{% for thread in subforum.thread_set.all %}
				<tr>
					<td>
						<a href="{% url 'forums:thread' thread.id %}"><strong>{{ thread.thread_name }}</strong></a><br>
						<p style="font-style: italic;font-size: 10px">{{ thread.created_by }} -- {{ thread.created_on }}</p>
					</td>
					<td>{{ thread.post_set.count }}</td>
					<td>{{ thread.views }}</td>
				</tr>
				{% endfor %}
				{% else %}
				<p>No threads are available.</p>
				{% endif %}
			</tbody>
		</table>		
	</div>
</body>
</html>

vozfake/forums/templates/forums/thread.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ thread.thread_name }}</title>
	{% load static %}
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'forums/vozfavicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'forums/vozfavicon-16x16.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'forums/bootstrap.min.css' %}">
</head>
<body style="background-color: black">
	<div class="container">
		<a href="{% url 'forums:index' %}">
			<img src="{% static 'forums/vozlogo.gif' %}" border="0" alt="vozForums" width="184" height="90" title="vozForums">
		</a>
	</div>
	<div class="container bg-white">
		<h4>
			<a href="{% url 'forums:index' %}">Forum</a>
			 > <a href="{% url 'forums:sub_forum' thread.parent.id %}">{{ thread.parent.sub_forum_name }}</a>
			 > {{ thread.thread_name }}
		</h4>
		<p style="font-style: italic;font-size: 10px">Created by: {{ thread.created_by }} -- {{ thread.created_on }}</p>
	</div>
	<div class="container bg-white">				
		<p>{{ thread.thread_content }}</p>
	</div>
</body>
</html>